.\"
.TH GPG-MAILKEYS 1 "Nov 23, 2010"
.SH NAME
.B gpg\-mailkeys
\- sends emails containing keys to their owners
.SH SYNOPSIS
.B gpg-mailkeys
.RI id ...
.SH DESCRIPTION
.B gpg-mailkeys
sends the owners of the keys listed on the command line a mail each,
containing their public key. After signing, you can use this tool to send
everyone the new signatures they just got.

If you're interested in encrypting the signature before it's sent, in order
to verify that the associated address actually belongs to the key owner,
you should check out
.B caff
.SH OPTIONS
None
.SH ENVIRONMENT
.TP 13
.I NAME
Set the name to use when sending messages
.TP 13
.I EMAIL
Set the email address to use when sending messages
.TP 13
.I SUBJECT
Set the subject of the messages you send
.TP 13
.I TEXT
Set the body text of the messages
.TP 13
.I SENDMAIL
Set the path to sendmail. Default: /usr/sbin/sendmail
.TP 13
.I SENDMAIL_ARGS
Set arguments to pass to $SENDMAIL. This can be useful to set
credentials in order to authenticate to an smtp server when using ssmtp
for example.
.TP 13
.I HOME
Set the default home directory.
.TP 13
.I GNUPGBIN
Set the gpg binary.  Default: "gpg".
.TP 13
.I GNUPGHOME
Set the default working directory for gpg.  Default: "~/.gnupg".

.SH FILES
The behavior of
.B gpg-mailkeys
can be updated through some files available in the user home directory.

Thus,
.B ~/.gpg-mailkeysrc
allows the user to overwrite the default value for the above environment
variables, and any text in
.B ~/.signature
will be appended to the end of the body text of the message.

.SH SEE ALSO
.BR gpg (1), caff (1)
.SH AUTHOR
This manual page was written by Simon Richter <sjr@debian.org>.
