all:

install:
	install -D springgraph $(DESTDIR)/usr/bin/springgraph
	install -D -m644 springgraph.1 $(DESTDIR)/usr/share/man/man1/springgraph.1
	install -D -m644 README.springgraph \
		$(DESTDIR)/usr/share/doc/signing-party/README.springgraph

clean:
