.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SIG2DOT 1 "May 31, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sig2dot \- creates a .dot file from a GPG signature listing
.SH SYNOPSIS
.B sig2dot [OPTIONS] < input-file > output-file
.br
.SH DESCRIPTION
This manual page documents briefly the
.B sig2dot
command.
Sig2dot parses the output of "gpg \-\-list\-sigs" and produces a .dot file
that can be used as input to a graphing program.
.SH OPTIONS
\fIsig2dot\fP
accepts the following options:
.TP 16
.B \-b
Black and white / do not colorize.
.TP 16
.B \-d <date>
Render graph as it appeared on <date> (ignores more recent
signatures).  Date must be in the format "YYYY\-MM\-DD".
Will also ignore keys that have since been revoked.
.TP 16
.B \-s <html-file-name>
Produces a sory HTML statistics file with the number of signatures per node.
.TP 16
.B \-a
Graph all keys, even if they do not have a signature
.TP 16
.B \-r "<key-revoked-string>"
Sets the text for the key-revoked string used by GnuPG. The default is 
what is used in the English version. This parameter can be set for versions 
of GnuPG localized to other languages. Default: "[revoked".
.TP 16
.TP 16
.B \-t "<title>"
Sets the title for the graph generated. Default: "Keyring Statistics".
.TP 16
.B \-u "<user-not-found-string>"
Sets the text for the user-not-found string used by GnuPG. The default is 
what is used in the English version. This parameter can be set for versions 
of GnuPG localized to other languages. Default: "[user id not found]".
.TP 16
.B \-q
Be quiet.
.TP 16
.B \-h
Print help and exit.
.TP 16
.B \-v
Print version and exit.
.SH EXAMPLE
gpg \-\-list\-sigs | sig2dot > sigs.dot
.sp 0
springgraph < sigs.dot > sigs.png
.SH SEE ALSO
.B springgraph(1)
.B gnupg(1)
.SH AUTHORS
Darxus@ChaosReigns.com with modifications by Kevin Rosenberg.
Versions 0.35 and later are by Christoph Berg <cb@df7cb.de>.
This manual page was written by Kevin M. Rosenberg <kmr@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
