all:

install:
	install -D keylookup $(DESTDIR)/usr/bin/keylookup
	install -D -m644 keylookup.1 $(DESTDIR)/usr/share/man/man1/keylookup.1
	install -D -m644 NEWS \
		$(DESTDIR)/usr/share/doc/signing-party/NEWS.keylookup

clean:
