.TH GPGPARTICIPANTS-PREFILL 1 "October 17, 2013"
.SH NAME
gpgparticipants-prefill \- insert checksum-digits in a gpgparticicpants' form
.SH SYNOPSIS
.B gpgparticipants-prefill
[\fIOPTIONS\fP] \fIEMPTYLIST\fP \fIFILLEDLIST\fP
.SH DESCRIPTION
.B gpgparticipants-prefill
takes a file produced by \fBgpgparticipants\fP (\fIEMPTYLIST\fP) and tries to fill in some
digits into the SHA256 field such that the resulting list actually has a SHA256
checksum that starts with those digits.  In other words, it tries to produce a
file that hashes to a checksum that is partially written down in the file.
Whenever a match is found, a file with the digits filled in is written to
\fIFILLEDLIST\fP\fB.\fP\fIDIGITS\fP.

.SH OPTIONS

.IP "\fB\-h\fP, \fB\-\-help\fP" 8
Print the usage text.

.IP "\fB\-\-fastforward\fP" 8
If a match is found of some length, immediately jump to the next length.

.IP "\fB\-\-min-length\fP \fINUM\fP" 8
Start search with given length.

.IP "\fB\-\-max-length\fP \fINUM\fP" 8
Stop search after the given length.

.IP "\fB\-\-prefix\fP \fIPREFIX\fP" 8
Only consider hex strings starting with \fIPREFIX\fP.

.SH SEE ALSO
.BR gpgparticipants (1)
.SH AUTHOR
This manual page was written by Stefan Huber <shuber@sthu.org>.
