.TH GPGPARTICIPANTS 1 "March 05, 2008"
.SH NAME
gpgparticipants \- generate paper list for keysigning party
.SH SYNOPSIS
.B gpgparticipants
.RB [\fIOPTIONS\fR]
{input|-}
{output|-}
datestring
organizer
title
.SH DESCRIPTION
.B gpgparticipants
is targeted at organisers of a keysigning party that uses the
Zimmermann-Sassaman key-signing protocol.

It creates a file with all the keys from a list of participators in your
keysigning party. You give it a list with key ID's and some general variables,
and it will generate a file you can publish. You publish this list;
participants will download and print this file to take with them to the party.

.SH OPTIONS

.TP
.BI -a \fIHASHES\fR,\ \fB--algorithm=\fIHASHES\fR

For each algorithm in \fIHASHES\fR, a comma-separated list of digest
algorithms supported by \fBgpg\fR(1), add a placeholder for the digest
value (to be filled by the participants) to the output file.  Default:
SHA256,RIPEMD160.

.SH EXAMPLES

To create a KSP file with all keys present in the keyring:

    gpg --with-colons --fingerprint | grep ^fpr: | cut -d: -f 10 | \\
        gpgparticipants - ksp-file.txt "20080222 1100" "My Name <my.name@my.mail>" "my party 08"

.SH SEE ALSO
.BR gpg (1), gpgsigs (1)
.SH AUTHOR
This manual page was written by Thijs Kinkhorst <thijs@debian.org>.
